#!/usr/bin/env -S mise tool-stub

tool = "azul-zulu"
version = "17.60.17"

[platforms.linux-x64]
url = "https://cdn.azul.com/zulu/bin/zulu17.60.17-ca-jdk17.0.16-linux_x64.tar.gz"
checksum = "blake3:d2784012b15e70ac8426e5cd72e61b10f5c38bb0c9a253ee4fe147a84a4dea94"
size = 198700362 # 189.50 MiB

[platforms.linux-arm64]
url = "https://cdn.azul.com/zulu/bin/zulu17.60.17-ca-jdk17.0.16-linux_aarch64.tar.gz"
checksum = "blake3:54f585b5b8479c3d269341017fa77f18cd8ff68ac44f9324d5ba8f3431d8b6bb"
size = 198590696 # 189.39 MiB

[platforms.darwin-x64]
url = "https://cdn.azul.com/zulu/bin/zulu17.60.17-ca-jdk17.0.16-macosx_x64.tar.gz"
checksum = "blake3:bfe1b3fc5be5361412ad4f7140cf3a6f66105d052ef5957f31273f595e5a0089"
size = 194313773 # 185.31 MiB

[platforms.darwin-arm64]
url = "https://cdn.azul.com/zulu/bin/zulu17.60.17-ca-jdk17.0.16-macosx_aarch64.tar.gz"
checksum = "blake3:b35ba3e64d2aef1f44ba355e6849de6e1d19629ffdfc4071d22b3cf2a4840100"
size = 192274740 # 183.37 MiB

[platforms.windows-x64]
url = "https://cdn.azul.com/zulu/bin/zulu17.60.17-ca-jdk17.0.16-win_x64.zip"
checksum = "blake3:3eeb6819f2b0dd4c1cd3810593f2de7f8ea65464fe428638160f79708c5f778f"
size = 196441390 # 187.34 MiB

[platforms.windows-arm64]
url = "https://cdn.azul.com/zulu/bin/zulu17.60.17-ca-jdk17.0.16-win_aarch64.zip"
checksum = "blake3:e44aed12cd51277b8dd2b5f51572a88e3f2e83910f2f15b7e43bd74d1af6a2df"
size = 184264663 # 175.73 MiB
