[tools]
go = "latest"
lua = "latest"
"oci:docker.io/jbadeau/maven" = "3.9.12"
oras = "latest"
python = "latest"
yq = "latest"

[tasks.init]
description = "Init"
run = "mise plugin link oci $PWD --force"

[settings]
experimental=true
