#!/usr/bin/env -S mise tool-stub

tool = "helmfile"
version = "1.2.3"

[platforms.linux-x64]
url = "https://github.com/helmfile/helmfile/releases/download/v1.2.3/helmfile_1.2.3_linux_amd64.tar.gz"
checksum = "blake3:1017a0d29e61ac936d1714a44f4248e502561b2066e37da2e8d3fb5f0413e1e5"
size = 42255415 # 40.30 MiB
bin = "helmfile"

[platforms.linux-arm64]
url = "https://github.com/helmfile/helmfile/releases/download/v1.2.3/helmfile_1.2.3_linux_arm64.tar.gz"
checksum = "blake3:dfb707d896fb88a76e7999703110793b147ec583b883345293ca69443944cd2d"
size = 38507246 # 36.72 MiB
bin = "helmfile"

[platforms.darwin-x64]
url = "https://github.com/helmfile/helmfile/releases/download/v1.2.3/helmfile_1.2.3_darwin_amd64.tar.gz"
checksum = "blake3:852356b430f72924a060c0119fb61b292accd2121415c5078ae9fa4641d389df"
size = 43104995 # 41.11 MiB
bin = "helmfile"

[platforms.darwin-arm64]
url = "https://github.com/helmfile/helmfile/releases/download/v1.2.3/helmfile_1.2.3_darwin_arm64.tar.gz"
checksum = "blake3:b89afdff187114d3a0381383d6d4ac3205aacd3aa021e1a7389cd0ef0591335a"
size = 40533300 # 38.66 MiB
bin = "helmfile"

[platforms.windows-x64]
url = "https://github.com/helmfile/helmfile/releases/download/v1.2.3/helmfile_1.2.3_windows_amd64.tar.gz"
checksum = "blake3:8cb2772538f83bcc4f97c473d3de84ad1b403f22de2090f0953f0802e3701cfb"
size = 43290555 # 41.29 MiB
bin = "helmfile.exe"
