#!/usr/bin/env -S mise tool-stub

tool = "nvim-surround"
version = "3.1.8"
category = "nvim-plugin"

[env]
NVIM_MISE_PLUGINS = "{{ install_path }}:{{ NVIM_MISE_PLUGINS }}"

[platforms.linux-x64]
url = "https://github.com/kylechui/nvim-surround/archive/refs/tags/v3.1.8.tar.gz"
checksum = "blake3:869a628b2e097aac5f2fd11774f1b4e807021c57e996cf592ecb2bd4cbad78a8"
size = 45752 # 44.68 KiB

[platforms.darwin-arm64]
url = "https://github.com/kylechui/nvim-surround/archive/refs/tags/v3.1.8.tar.gz"
checksum = "blake3:869a628b2e097aac5f2fd11774f1b4e807021c57e996cf592ecb2bd4cbad78a8"
size = 45752 # 44.68 KiB

[platforms.windows-x64]
url = "https://github.com/kylechui/nvim-surround/archive/refs/tags/v3.1.8.tar.gz"
checksum = "blake3:869a628b2e097aac5f2fd11774f1b4e807021c57e996cf592ecb2bd4cbad78a8"
size = 45752 # 44.68 KiB
